version: 2
updates:
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    rebase-strategy: auto
    schedule:
      timezone: 05:00 UTC
    assignees:
      - "kampfmoehre"
  - directory: /
    open-pull-requests-limit: 10
    package-ecosystem: npm
    rebase-strategy: auto
    schedule:
      timezone: 05:00 UTC
    assignees:
      - "kampfmoehre"
